---
name: Format with Stylua
on: [push, pull_request]
jobs:
  stylua-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Stylua
        run: |
          pushd "$(mktemp -d)"
          curl -OL https://github.com/JohnnyMorganz/StyLua/releases/download/v0.13.1/stylua-linux.zip
          unzip stylua-linux.zip
          chmod +x stylua
          sudo mv stylua /bin/stylua
          popd

      - name: Lint with stylua
        run: |
          stylua lua/
          git diff HEAD

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format code with Stylua
