---
name: Render documentation with vimhelp
on:
  push:
    branches:
      - main
jobs:
  vimhelp-render-html-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Render documentation with vimhelp
        uses: 9999years/vimhelp@main
        with:
          doc_directory: doc/
          output_directory: public/

      - run: |
          sudo chown -R $USER public/
          cp public/batteries.txt.html public/index.html
          echo "Pages to deploy:"
          ls -l public/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: public/
